name: Build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build with MSVC
      run: |
        # Add your build commands here
        cl /I"path\to\includes" /L"path\to\libs" src\main.c /Fe:MyApp.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Zig
      run: |
        wget https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1234+abcdef123.tar.xz
        tar -xf zig-linux-x86_64-0.11.0-dev.1234+abcdef123.tar.xz
        echo "$PWD/zig-linux-x86_64-0.11.0-dev.1234+abcdef123" >> $GITHUB_PATH
    - name: Build with Zig for Linux
      run: |
        zig cc -target x86_64-linux-gnu -I/path/to/includes -L/path/to/libs src/main.c -o MyAppLinux

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        unzip commandlinetools-linux-6609375_latest.zip -d $HOME/android-sdk
        echo "$HOME/android-sdk/cmdline-tools/bin" >> $GITHUB_PATH
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;21.3.6528147"
    - name: Build APK with Gradle
      run: |
        # Assuming you have a Gradle wrapper in your repository
        ./gradlew assembleRelease
